# Refer to the wiki for more information - https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

background {
    monitor = 
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
}

label {
    monitor = DP-2
    text = $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 30
    font_family = JetBrainsMono Nerd Propo Bold

    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor = DP-2
    text = cmd[update:1000] echo "<span foreground='##C8C8C8'>$(date)</span>"
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = JetBrainsMono Nerd Propo Medium

    position = 0, 40
    halign = center
    valign = center
}

input-field {
    monitor = DP-2
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}
shape {
    monitor = DP-2
    size = 150, 60  # horizontal, vertical
    color = rgba(0, 0, 0, 0.0) # no fill
    rounding = -1 # circle
    border_size = 4
    border_color = rgba(0, 207, 230, 1.0)

    position = 0, -200
    halign = center
    valign = center
}

label { # Power off widget
    monitor = DP-2
    text = ⏻
    onclick = systemctl poweroff
    color = rgba(0, 207, 230, 1.0)
    font_size = 20
    position = 0, -200 
    halign = center
    valign = center
}
label { # Reboot widget
    monitor = DP-2
    text = ⟳
    onclick = systemctl reboot
    color = rgba(0, 207, 230, 1.0)
    font_size = 20
    position = 40, -200 
    halign = center
    valign = center
}
label { # Suspend Widget
    monitor = DP-2
    text = ⏾
    onclick = systemctl suspend
    color = rgba(0, 207, 230, 1.0)
    font_size = 20
    position = -40, -200
    halign = center
    valign = center
}

label { # Media Player
    monitor = DP-2
    text = cmd[update:1000] ~/.config/hypr/scripts/media.sh
    onclick = playerctl play-pause
    color = rgba(0, 207, 230, 1.0)
    position = 0, -300
    halign = center
    valign = center
}

label { # Logo for primary monitor
    monitor = DP-2
    text = cmd[update:1000] ~/.config/hypr/scripts/logo.sh
    color = rgba(0, 207, 230, 1.0)
    font_family = monospace 
    text_align = left
    position = 0, 400
    halign = center
    valign = center
}
label { # Logo for secondary monitor
    monitor = DP-1
    text = cmd[update:1000] ~/.config/hypr/scripts/logo.sh
    color = rgba(0, 207, 230, 1.0)
    font_family = monospace 
    text_align = left
    position = 0, 0
    halign = center
    valign = center
}

label { # Displays weather
    monitor = DP-2
    text = cmd[update:1000] ~/.config/hypr/scripts/get_weather.sh
    color = rgba(0, 207, 230, 1.0)
    position = -850, -500
    halign = center
    valign = center
}
